### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by mikesprague** [CU-CommunityApps/ct-azure-openai-gpt4-chat#53]
Intermittent error, first reported yesterday,

Unable to reproduce at first, I've since been able to with the prompt: `show me an es6 generator in js`

Error on page:
`Application error: a client-side exception has occurred (see the browser console for more information).`

Error content from browser console:

```js
Error: marked(): input parameter is undefined or null
Please report this to https://github.com/markedjs/marked.
    at Marked.parse (689-9b6a1ec9ea44ea98.js:30:7486)
    at marked (689-9b6a1ec9ea44ea98.js:30:8403)
    at markdownToText (page-8ba03c29f0c57a5b.js:1:9907)
    at pre (page-8ba03c29f0c57a5b.js:1:13456)
    at Mf (fd9d1056-fc215812d5e2fa90.js:9:39686)
    at rC (fd9d1056-fc215812d5e2fa90.js:9:112346)
    at Jk (fd9d1056-fc215812d5e2fa90.js:9:102245)
    at Ik (fd9d1056-fc215812d5e2fa90.js:9:101422)
    at df (fd9d1056-fc215812d5e2fa90.js:9:101240)
    at ef (fd9d1056-fc215812d5e2fa90.js:9:98669)
window.console.error @ 2472-7918ce866bb273fc.js:1
```

**Comment by mikesprague** [comment]
In the recently added copy to clipboard button on individual code blocks, it seems there's times no content gets passed in during renders. I think this can probably by short-circuiting the `markdownToText` helper method if no content is supplied.
